#!/usr/bin/env python
import sys
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE,SIG_DFL) 

### this script input a list of file names, output the simplified version of the file names. 
## eg. ls mEncode_Forbrain_*.bed | aka   -->    Forbrain_*.bed



List = []
for line in sys.stdin.readlines():
	List.append(line.strip())

if len(List)==1:
	List = List[0].split()

# same head from range(0,pos)?
def sameHead(List, pos):
	refL = List[0]
	for l in List[1:]:
		if l[:pos]!=refL[:pos]:
			return False
	return True

# if all diff, return -1. eg. abcc, abac. return 1
def maxSamePos(List):
	minLen = min([len(l) for l in List])
	for pos in range(minLen+1):
		if not sameHead(List, pos):
			return pos-1
	return pos

def trimList(List, pos1, pos2=0):
	return [l[pos1:len(l)-pos2] for l in List]

pos1 = maxSamePos(List)
pos2 = maxSamePos([l[::-1] for l in List])


for l in trimList(List, pos1, pos2):
	sys.stdout.write(l+"\n")



