#!/usr/bin/env python
# encoding: utf-8


## list/goto kw
## usage: s kw
## 		cd dr linked to the kw.
## usage: s
## 		show all current kw:dir


from pathlib import Path
from sys import argv
import os


HOME = str(Path.home())

## load existing
datFile = "{}/bin/sd/sd.dat".format(HOME)
kw2dr = {}
with open(datFile) as f:
	for l in f.readlines():
		ls = l.strip().split()
		kw, dr = ls[0], ls[1]
		kw2dr[kw] = dr

## 
def printDict(d):
	for key, item in d.items():
		print("{}\t{}".format(key, item))

	pass


## get input, cd into dr linked to the kw
try:
	kw = argv[1]
	try:
		dr = kw2dr[kw]
		os.chdir(dr)
	except KeyError:
		print("{} is not assigned".format(kw))
		printDict(kw2dr)

## if no kw is give, list all current kw:dir
except IndexError:
	printDict(kw2dr)




