#!/usr/bin/env python
# encoding: utf-8


## useage: sd kw [dr]
## save [dr] to kw. dr default to cwd. 


from pathlib import Path
from sys import argv

HOME = str(Path.home())

## load existing
datFile = "{}/bin/sd/sd.dat".format(HOME)
kw2dr = {}
with open(datFile) as f:
	for l in f.readlines():
		ls = l.strip().split()
		kw, dr = ls[0], ls[1]
		kw2dr[kw] = dr

## get input
kw = argv[1]
try:
	dr = argv[2]
except IndexError:
	dr = Path().absolute()  # cwd

## set new
kw2dr[kw] =  dr

## write back to datFile
towrite = "\n".join(["{}\t{}".format(kw, dr) for kw, dr in kw2dr.items()]) + "\n"
with open(datFile, "w") as f:
	f.write(towrite)
