#!/bin/bash
set -ue

## save dir to kw in configFile
## usage: ss $kw [$dir]


sdPath="$HOME/bin/sd"
configFile="$sdPath/sd.dat"

## check input args
if [ $# -eq 0 ]; then
	# no arg
	echo "needs to provide at least the kw as \$1"
	exit
elif [ $# -eq 1 ]; then
	# 1st arg -> kw
    kw=$1
	dir=`pwd`
else
	# 1st arg -> kw, 2nd arg -> dir
	kw=$1
	dir=`realpath $2`
fi

## check kw
if $kw &>/dev/null ; then
	echo "kw='$kw' is a reserved keyword, skipped. Please fix at $configFile";
	exit
else
	echo "Setting directory shortcut:"
	echo "$kw  ->  $dir"
	alias $kw="cd '$dir'"
	echo "source ~/.bash_profile"
	echo "to refresh"
fi

## check if $kw exist in $configFile
awk -F $'\t' -v kw="$kw" -v dir="$dir" -v OFS="\t" '
	BEGIN {found=0}
	{if($1==kw){print kw, dir; found=1} else {print $0}}
	END {if(found==0){print kw, dir}}' $configFile > tmp; mv tmp $configFile

